app/models.py
from app import db

class Product(db.Model):
    __tablename__ = "EK"

    ID = db.Column(db.Integer, primary_key=True)
    Produkt = db.Column(db.TEXT, nullable=False)
    Vorhanden = db.Column(db.Integer)
    Krit = db.Column(db.Integer, nullable=False)

    def __repr__(self):
        return '<Product: {}>'.format(self.name)

class Beer(db.Model):
    __tablename__ = "Bier"

    id = db.Column(db.Integer, primary_key=True)
    NAME = db.Column(db.TEXT, nullable=False)
    Anzahl = db.Column(db.Integer)
    Strichcode = db.Column(db.String(255))

    def __repr__(self):
        return '<Beer: {}>'.format(self.name)

class Senseo(db.Model):
    __tablename__ = "Kaffeemaschine"

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String)
    status = db.Column(db.Boolean)

app.py
#/usr/bin/python2

from flask import Flask, render_template, request, url_for
import subprocess
from datetime import datetime
import time
from threading import Thread
import sqlite3
from flask import g

'----------------------> Helpers <-----------------------------'
def write_file(path, value):
    try:
        with open(path,'w') as file:
            file.write(value)
    except: 
	print "Fehler"
	pass


DATABASE = '/home/pi/Data.db'

def get_db():
    db = getattr(g, '_database', None)
    if db is None:
        db = g._database = sqlite3.connect(DATABASE)
    return db

def timer(h,m):
    while True:
        dt = list(time.localtime())
        hour = dt[3]
        minute = dt[4]

        if hour == h and minute == m:
	    #Maschine starten
            write_file("/sys/class/gpio/gpio22/direction", "out")
            write_file("/sys/class/gpio/gpio22/value","1")
            time.sleep(2)
            write_file("/sys/class/gpio/gpio22/value","0")
	    time.sleep(60)
	    #Kaffee rauslassen
	    write_file('/sys/class/gpio/gpio23/direction','out')
            time.sleep(30)
            write_file('/sys/class/gpio/gpio23/direction','in')
	    time.sleep(5)
	    #Maschine aus
	    write_file("/sys/class/gpio/gpio22/direction", "out")
            write_file("/sys/class/gpio/gpio22/value","1")
            time.sleep(2)
            write_file("/sys/class/gpio/gpio22/value","0")
	    print 'Timer muede, timer fertig...'
            break


'-----------------------> Initialisierung <--------------------'
write_file('/sys/class/gpio/export','23')
write_file('/sys/class/gpio/export','22')


app = Flask(__name__)


@app.route('/', methods=['GET','POST'])
def do():
    on_off = request.args.get('on_off')
    go = request.args.get('go')
    alarm_time = request.args.get('time')
    
    if go is not None:	
	write_file('/sys/class/gpio/gpio23/direction','out')	
	time.sleep(5)
        write_file('/sys/class/gpio/gpio23/direction','in')
    	return 'Hmmmm chafe.. nom nom'

    if on_off is not None:
        write_file("/sys/class/gpio/gpio22/direction", "out")
        write_file("/sys/class/gpio/gpio22/value","1")
	time.sleep(5)
	write_file("/sys/class/gpio/gpio22/value","0")
       	return 'haeaseasea...'

    if alarm_time is not None:
        alarm_h = int(alarm_time[:2])
        alarm_m = int(alarm_time[3:])
        timer_thread = Thread(target=timer, args=(alarm_h, alarm_m,))
        timer_thread.start()
        return 'Timer gesetzt'
	return render_template('form.html')

	
if __name__ == "__main__":
    app.run(host='0.0.0.0',port=1337)

app/__init__.py
# third-party imports
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_bower import Bower

# local imports
from config import app_config

# db variable initialization
db = SQLAlchemy()
migrate = Migrate()
bower = Bower()

def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(app_config[config_name])
    db.init_app(app)
    migrate.init_app(app, db)
    bower.init_app(app)
    from app import models
    from .home import home as home_blueprint
    app.register_blueprint(home_blueprint)

    return app

app/home/__init__.py
from flask import Blueprint

home = Blueprint('home', __name__)

from . import views

app/home/views.py
from flask import render_template, request, current_app, flash

from . import home
from ..helpers import coffee
from ..models import Product, Beer, Senseo
from app import db

@home.route('/')
def shopping():
    """
    Render the homepage template on the / route
    """
    return render_template('home/index.html', title="Welcome to Kaffier")


@home.route('/beer')
def beerpage():
    """
    Render the dashboard template on the /beer route
    """
    products = Product.query.all()
    beers = Beer.query.all()
    return render_template('home/beer.html', title="Beer", products=products, beers=beers)


@home.route('/coffee', methods=['GET'])
def coffeepage():
    """
    Render the dashboard template on the /coffee route
    """
    coffeemachine = Senseo.query.get(1)
    return render_template('home/coffee.html', title="Coffee", status=coffeemachine.status)

@home.route('/coffee', methods=['POST'])
def coffeeaction():
    """
    Action!!!
    """
    error = None
    success = None
    coffeemachine = Senseo.query.get(1)
    if coffee.initialize():
        params = request.form
        if params['power-button']:
            if coffee.on_off():
                if coffeemachine.status:
                    success = "Device is now off."
                    coffeemachine.status = False
                else:
                    success = "Device is now on."
                    Senseo.status = True
                db.commit()
            else:
                error ="Can not turn off/on the device."
    else:
        error = "Could not initialize the coffe machine."
    if error:
        flash(error, "danger")
        current_app.logger.error(error)
    if success:
        flash(success, "success")
        current_app.logger.info(success)
    status = coffeemachine.status

    return render_template('home/coffee.html', title="Coffee", status=status)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{{ title }} | Kaffier</title>

    <link rel="stylesheet" href="{{ url_for('bower.static', filename='bootstrap/dist/css/bootstrap.css') }}" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css" crossorigin="anonymous">
    <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">
    <link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon.ico') }}">
</head>
<body>

  <section id="hero">
    <div class="hero-container">
      <div class="wow fadeIn">
        <div class="hero-logo">
          <img class="" src="{{ url_for('static', filename='img/logo.png') }}" alt="Imperial">
        </div>
        <h1></h1>
        <h2><span class="rotating">Tim für sexy Zungen in prallen Galaxien, Stark und zufrieden. Unverzichtbar für Weltbürger vögeln mit Manu</span></h2>
        <div class="actions">
          <a href="#services" class="btn-services">Services</a>
        </div>
      </div>
    </div>
  </section>

  <header id="header">
    <div class="container">
      <div id="logo" class="pull-left">
        <a href="#hero"><img src="{{ url_for('static', filename='img/logo.png') }}" alt="" title="" /></img></a>
      </div>
      <nav id="nav-menu-container">
        <ul class="nav-menu">
          <li class="menu-active"><a href="#hero">Home</a></li>
          <li><a href="#services">Services</a></li>
          <li><a href="#portfolio">Galerie</a></li>
          <li><a href="#team">Die Crew</a></li>
        </ul>
      </nav>
      <!-- #nav-menu-container -->
    </div>
  </header>

  <section id="services">
    <div class="container wow fadeInUp">
      <div class="row">
        <div class="col-md-12">
          <h3 class="section-title">Unsere Dienste</h3>
          <div class="section-title-divider"></div>
          <p class="section-description">Unsere atemberaubenden, tollen, unglaublichen Dienste</p>
        </div>
      </div>
      <div class="row">
        <div class="col-md-4 service-item">
	        <div class="service-icon"><i class="fa fa-beer"></i></div>
          <h4 class="service-title"><a href="{{ url_for('home.beerpage') }}">Bier</a></h4>
          <p class="service-description">Finde heraus wer am meisten Bier trinkt</p>
        </div>
        <div class="col-md-4 service-item">
          <div class="service-icon"><i class="fa fa-coffee"></i></div>
          <h4 class="service-title"><a href="{{ url_for('home.coffeepage') }}">Kaffee</a></h4>
          <p class="service-description">Lass dir ein Kaffee heraus, wann immer du willst.</p>
        </div>
        <div class="col-md-4 service-item">
          <div class="service-icon"><i class="fa fa-shopping-basket"></i></div>
          <h4 class="service-title"><a href="{{ url_for('home.shopping') }}">Einkaufsliste</a></h4>
          <p class="service-description">Was wird noch gebraucht?</p>
        </div>
        <div class="col-md-4 service-item">
          <div class="service-icon"><i class="fa fa-cutlery"></i></div>
          <h4 class="service-title"><a href="#">Pizza Datenbank</a></h4>
          <p class="service-description">Finde heraus welche Pizza schon erfasst wurde</p>
        </div>
      </div>
    </div>
  </section>


  <section id="team">
    <div class="container wow fadeInUp">
      <div class="row">
        <div class="col-md-12">
          <h3 class="section-title">Die Crew</h3>
        </div>
      </div>
      <div class="row">
        <div class="col-md-3">
          <div class="member">
            <div class="pic">
              <img src="{{ url_for('static',filename='img/team-1.jpg') }}" alt="">
            </div>
            <h4>Hugo</h4>
            <span>CEO</span>
          </div>
         </div>

        <div class="col-md-3">
          <div class="member">
            <div class="pic">
              <img src="{{ url_for('static', filename='img/team-2.jpg') }}" alt="">
            </div>
            <h4>Tim</h4>
            <span>CEO</span>
          </div>
         </div>

        <div class="col-md-3">
          <div class="member">
            <div class="pic">
              <img src="{{ url_for('static', filename='img/team-3.jpg') }}" alt="">
            </div>
            <h4>Manu</h4>
            <span>CEO</span>
          </div>
        </div>
      </div>
    </div>
  </section>
  <footer id="footer">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="copyright">
            &copy; Copyright <strong>phreeek productions</strong>. All Rights Reserved
          </div>
        </div>
      </div>
    </div>
  </footer>

  <a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>

  <!-- Required JavaScript Libraries -->
		<script src="{{ url_for('bower.static', filename='jquery/dist/jquery.js') }}"></script>
		<script src="{{ url_for('bower.static', filename='bootstrap/dist/js/bootstrap.js') }}"></script>
		<script src="{{ url_for('bower.static', filename='superfish/dist/js/hoverIntent.js') }}"></script>
		<script src="{{ url_for('bower.static', filename='superfish/dist/js/superfish.min.js') }}"></script>
		<script src="{{ url_for('bower.static', filename='Morphext/dist/morphext.min.js') }}"></script>
		<script src="{{ url_for('bower.static', filename='wow/dist/wow.min.js') }}"></script>
		<script src="{{ url_for('bower.static', filename='stickyjs/stickyjs.js') }}"></script>
		<script src="{{ url_for('bower.static', filename='jquery.easing/js/jquery.easing.js') }}"></script>
		<script src="{{ url_for('bower.static', filename='moment/moment.js') }}"></script>
		<script src="{{ url_for('bower.static', filename='eonasdan-bootstrap-datetimepicker/src/js/bootstrap-datetimepicker.js') }}"></script>
		<script src="{{ url_for('static', filename='js/timepicker.js') }}"></script>
		<script src="{{ url_for('static', filename='js/custom.js') }}"></script>
</body>
</html>

app/templates/form.html
<html>
    <head>
        <title>MySenseo</title>
        <link rel=stylesheet type=text/css href="{{ url_for('static', filename='style.css') }}">
    </head>
    <body>
        <div id="container">
            <div class="title">
                <h1>My Senseo Remote</h1>
            </div>
            <div id="content">
                <form method="GET" action="">
                  <input type="submit" value="go" name="go" />
                </form>

                <form method="GET" action="">
                  <input type="submit" value="on_off" name="on_off" />
                </form>

		<form>
		    Select a time:<input type="time" name="time" />
		    <input type="submit" value="timer" />
		</form>		
            </div>         		
        </div>
    </body>
</html>

app/templates/home/beer.html
{% extends "base.html" %}
{% block title %}Coffee{% endblock %}
{% block body %}
<div class="container">
    <div id="content">
        <h1 class="beer">Beers</h1>
				<table class="table table-hover">
					<thead>
						<tr>
							<th>ID</th>
							<th>Name</th>
							<th>Quantity</th>
						</tr>
					</thead>
					<tbody>
						{% for beer in beers %}
							<tr>
								<td>{{ beer.id }}</td>
								<td>{{ beer.NAME }}</td>
								<td>{{ beer.Anzahl }}</td>
							</tr>
						{% endfor %}
					</tbody>
				</table>
        <h1 class="beer">My shopping list</h1>
				<table class="table table-hover">
					<thead>
						<tr>
							<th>ID</th>
							<th>Product</th>
							<th>Available</th>
						</tr>
					</thead>
					<tbody>
						{% for product in products %}
							<tr>
								<td>{{ product.ID }}</td>
								<td>{{ product.Produkt }}</td>
								{% if product.Vorhanden == 1 %}
									<td><i class="fa fa-check" aria-hidden="true"></i></td>
								{% else %}
									<td><i class="fa fa-times" aria-hidden="true"></i></td>
								{% endif %}
							</tr>
						{% endfor %}
					</tbody>
				</table>
    </div>
</div>

{% endblock %}

app/templates/home/coffee.html
{% extends "base.html" %}
{% block title %}Coffee{% endblock %}
{% block body %}
<div class="container">
    <div id="content">
				<h1 class="coffee">My Senseo Remote</h1>
				<div class="SenseoPanel">
            <form id="coffee-form-1" action="{{ url_for('home.coffeeaction') }}" method="post">
						    <button type="button" class="btn btn-rnd btn-rnd-little btn-rnd-left"></button>
                {% if status %}
						    <button type="submit" value="on_off" name="power-button" class="btn btn-rnd btn-rnd-big btn-rnd-middle device-on"><span class="glyphicon glyphicon-off"></span></button>
                {% else %}
						    <button type="submit" value="on_off" name="power-button" class="btn btn-rnd btn-rnd-big btn-rnd-middle device-off"><span class="glyphicon glyphicon-off"></span></button>
                {% endif %}
                <button type="button" class="btn btn-rnd btn-rnd-little btn-rnd-right"></span></button>
            </form>
        </div>
				<br />
				<div class="row">
            <form id="coffee-form-2" action="{{ url_for('home.coffeeaction') }}" method="post">
                <div class='col-sm-4'></div>
                <div class='col-sm-4'>
                    <div class="form-group">
                        <div class='input-group date' id='datetimepicker1'>
                            <input type='text' class="form-control" />
                            <span class="input-group-addon">
                                <span class="glyphicon glyphicon-calendar"></span>
                            </span>
                        </div>
                    </div>
                </div>
                <div class='col-sm-4'>
                    <button type="button" class="btn btn-primary" type="submit">Go</button>
                </div>
            </form>
				</div>
    </div>
</div>
{% endblock %}

app/templates/home/index.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block body %}
<div class="intro-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="intro-message">
                    <h1>Kaffier</h1>
                    <hr class="intro-divider">
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}